openapi: 3.0.0
info:
  title: ReqArchitect API
  version: 1.0.0
  description: API specification for ReqArchitect microservices

components:
  schemas:
    BaseResponse:
      type: object
      properties:
        success:
          type: boolean
        message:
          type: string
        data:
          type: object
        errors:
          type: array
          items:
            $ref: '#/components/schemas/ErrorDetail'
        pagination:
          $ref: '#/components/schemas/PaginationMetadata'
        request_id:
          type: string
      required:
        - success
        - message
        - request_id

    ErrorDetail:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
        field:
          type: string
        details:
          type: object
      required:
        - code
        - message

    PaginationMetadata:
      type: object
      properties:
        total_count:
          type: integer
        page:
          type: integer
        per_page:
          type: integer
        total_pages:
          type: integer
      required:
        - total_count
        - page
        - per_page
        - total_pages

  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

x-ratelimit:
  default:
    rate: 100
    per: 1 minute
    burst: 50
  endpoints:
    /api/v1/requirements:
      get:
        rate: 1000
        per: 1 minute
        burst: 200
      post:
        rate: 100
        per: 1 minute
        burst: 20
    /api/v1/analytics:
      get:
        rate: 50
        per: 1 minute
        burst: 10

x-circuitbreaker:
  default:
    failureThreshold: 50
    successThreshold: 10
    timeout: 30s
  services:
    requirements-service:
      failureThreshold: 30
      successThreshold: 5
      timeout: 15s

x-cache:
  default:
    ttl: 300s
  endpoints:
    /api/v1/requirements/{id}:
      ttl: 600s
    /api/v1/analytics/summary:
      ttl: 1800s
