version: '3.8'

services:
  jaeger:
    image: jaegertracing/all-in-one:1.40
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"  # UI port
      - "14268:14268"  # Collector HTTP port
      - "14250:14250"  # Collector gRPC port
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
    networks:
      - reqarchitect
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:16686"]
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  reqarchitect:
    external: true
