apiVersion: v1
kind: Secret
metadata:
  name: envoy-certs
  namespace: reqarchitect
type: Opaque
data:
  # These will be filled with actual base64-encoded certificates
  # Example: cat ca.crt | base64 -w0
  "ca.crt": "BASE64_ENCODED_CA_CERT"
  "envoy.crt": "BASE64_ENCODED_ENVOY_CERT"
  "envoy.key": "BASE64_ENCODED_ENVOY_KEY"
---
apiVersion: v1
kind: Secret
metadata:
  name: service-certs
  namespace: reqarchitect
type: Opaque
data:
  # These will be filled with actual base64-encoded certificates
  "ca.crt": "BASE64_ENCODED_CA_CERT"
  "strategy.crt": "BASE64_ENCODED_STRATEGY_CERT"
  "strategy.key": "BASE64_ENCODED_STRATEGY_KEY"
  "business-layer.crt": "BASE64_ENCODED_BUSINESS_LAYER_CERT"
  "business-layer.key": "BASE64_ENCODED_BUSINESS_LAYER_KEY"
  "user.crt": "BASE64_ENCODED_USER_CERT"
  "user.key": "BASE64_ENCODED_USER_KEY"
  "kpi.crt": "BASE64_ENCODED_KPI_CERT"
  "kpi.key": "BASE64_ENCODED_KPI_KEY"
  "initiative.crt": "BASE64_ENCODED_INITIATIVE_CERT"
  "initiative.key": "BASE64_ENCODED_INITIATIVE_KEY"
