global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'consul'
    metrics_path: '/v1/agent/metrics'
    params:
      format: ['prometheus']
    static_configs:
      - targets: ['consul:8500']
    metrics_path: '/v1/agent/metrics'
    scheme: 'http'
    params:
      format: ['prometheus']
    bearer_token: '${CONSUL_HTTP_TOKEN}'

  - job_name: 'consul-health'
    metrics_path: '/health'
    static_configs:
      - targets: ['consul:8500']
    scrape_interval: 10s
