"""Initial business case model

Revision ID: 972892404dd0
Revises: 
Create Date: 2025-05-17 23:05:16.502777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '972892404dd0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('justification', sa.Text(), nullable=True),
    sa.Column('expected_benefits', sa.Text(), nullable=True),
    sa.Column('risk_assessment', sa.Text(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('business_cases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_business_cases_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_business_cases_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('business_cases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_business_cases_user_id'))
        batch_op.drop_index(batch_op.f('ix_business_cases_tenant_id'))

    op.drop_table('business_cases')
    # ### end Alembic commands ###
